language: java
jdk: oraclejdk11
addons:
  apt:
    update: true
    sources:
      - deadsnakes
    packages:
      - python3.6
      - python3.6-dev

env:
  global:
  - secure: J2mRdXKv5w5xjLhKELT3zZL+ieH3ul2y85tNZqqqh2gchbpVe64q86JQWcYota87Ou7xpahfY4b1x8Y/oA20OsgKKWdk2ttc5lJjPkfg8MAAfLlAlJmNH3UmkOo+xfyUh1ltrJ9ndfQGAvis75qijysk1VEGRanJUUJW7nYHI+Hy+6kW7UDDsMSg5arXNdak9pJsjb03yXIrTNbo1xMZ0h0UdFAetm0utA7SIlA7WvSNcd0RkD/W39D5DbRd4UTGGjMHJ1Q4NeAngDmXJCVTzq6jwCeGt/9qJyoCfOYOhtrW0WNVXLkyyTxcgxl5JUyjmfmEo3MaqAbnzOpjncy95YzG9A6maAqnQ36zzvg4idIQLJ6AsXF5mz3OqvMVB7SleEZVjK+JEPtMMGQg5N3TICTkjce7aop/MiqyDXdol1HUl1hAPYmD2BpUcEyCZYQbfCpCRoW8uZ1W4TBad5mDCK+m+jIdlk1AAavTYsrgspM5riGEVyQazTsFJuYm1/E/syCpecl8oDjYelchfsueve9m8DrOJccnATBDOHsqZsl+eJLyfnH8xrWTFrtCms395C3jqojaZ3taVNZTq4x/etBO+Kfgx/u0KYp3iJmVDl5LmMfFgQaL3zClbSQBPi9EPs22cP2rasIl08GGlXq8k7WBidPVMzawAuBdWTLn6Dg=
  - # SONATYPE_USERNAME
  - secure: uVwxpE6PZ4F4++Q8RuWE/i7mwaOFmlKqxWL1PRQpaFXvyl4r+r9O6WkbCk9heZRRZKEquXnWuYxwuhYFcH81BCYbswu5PNfPFGig28gwTA92+suhUXDF10/t3KmsLakydQIwEgXYBW7TwAdaBg8dC7X+WqQ2CFm7SCwbUp3T49ULWP8mA1St+CGOB7fIgA5a1r3dmwY/cID3qJ3R3p/QuHFpeOG230hPPtwrTXiLsuZy79pXdn/xW/p/WGT5Pdz13ANUKUq+kGLeqkgdCowOpEqLPFWU9LvoTN12El236c01soFZ/vsKI7cuN+2hGIHCq2xoiSUZOB3lUgyppmavb8OEh9FmUX2CquYnyYU9/0jL6M9CxVKB3fdCp3KXgjLyw5/94o/rHL9THJcTctH2KQl5MkqKSA9qr+b2i/5HatrVCj9SYAoM2qhYg6xqQigEBKPNCG6zr4JFedBMYDB1vnrPfzSc8pwYIKiVGr864wwTyeAvRLEKnccLx1LDvt+lRO5DBhDdVjVIUOGHwVvpohgBDeOKP9vO49GHEid3sOM19+gQbymnz4zApaApPoOI5o5L6M3Xd6XrZ4efcb3bPMCQ/G/VJ0UNRi+16mGMIL0WOMlmPhH8QKlXdNZz4psL7b3Pfo5UyaILxWXjnJiZGuYrPTQnRh4rIsjuOBkg2qE=
  - # SONATYPE_PASSWORD
  - secure: N2ZhlO6mt5ZQ1bh5eQhcPoP8IUYi50XSO8W0WmylC3HA5GNYeBlUtJKN8xpc0g7pCViMHU1wHNQLhgo0N9XEAERpY+udYRsBgu2B1/1owh0ve0a8E1DkhSE5ysp3VFjrAPzzQxRFpYRIiaRErbnPqPYFKyI+1lI6fy6MDbSUQsQzrXWe0jAH+s36v36cFvckOGaWe/vVkmZm+AH0rReO+ZT9/3fAereIcwhP+gUz+hjHf0fLTiTV0917rYI+fZgyVDBs7Z3JxIJbPenKSMTHrLCvQWDx39q3CuwvAMVMbBDYKJmn1JNGc6ofKypuHkMmzDFzmUyhse2yj2eqBsWRUc7fQUsdR//B8wgfGyHnEgZcLkh+oj+bFoww2asFZMDe7FGFyddPgCH8ky9ASg9mMHfHMzowjOaSojG2eATqwupYg+2fAGPty4Z7i6up819QvELoI+0G80trmScOjyfpqXaC4iCL+wGSGM4y7b6HS4mwHZx9B55KGEJHExKbFB1bglw+TI5NOgvUf1FkhMpoSqTa8n0gthNDE5yVC2Qvcr6AmhUZFoTSIfv/fMA6M6FfMGoKq56DlZfrDEgNjdq6ZW8SMZ/qjJe7EAbDLRkiBctXoc0hwsWoShu+MQL3AY7KITYUlAYYom3UZcsHrNkfTuffFlfumLGGcDMu+YUGF2w=
  - # GPG_KEY_NAME
  - secure: pxYxmA/9xS/9DO6rUAhlbAtYQMmG633jSwG8OIVCnnoQSXS4UILJgNl7Q6dQsAuT27tk+/fin0kXTnxWqCe0URb3c3XgNQwfGAuz1JIYVPHvezoDQLLRQA6LRgqd7GuvBDsyXJvBANozGKJYJVfoeT9gqFosFuMdRZ88eQm+ltX7zVKyMiz2rqKYPoSFInNxDGMOaIQ+RZdf8ai8rLY3E11PxsMC0LgypEDbuC7d9Q+Tu89YfUeuRly0hAuxmW++RrMgeeAs/7BndmZqcHVpkrcX6Drq8nZ2cj0ev4IDJelV/Nd17Vjfg7HgfJ4/d9S+PCg4KhvOY/y9Xad8geIIzXLFD9ZgcaK7MT9+BFGYXj7ExizFSc+Ico5Q822RJA1XZWfc/EgnY+7jEZCCMz/ceHx8oSh0ce1VbPl7c+O+jMXUMQC69Gpys57XC48rdPn0bbjc4/jpSOq46Xv7YdcGuA2BcWEEeQ0WAbi9IDcevpCXiZ7kng5hHTCpfaYVhn63KAIAMKf7tu6C78wFZR63F8Gf4x/jKE37QqvHV3uOzD7ar6nTAuy/ukZK0p4zyeIYe25PnS9K4kpolT1I12i7/l/7MO9NPFdB0aOCBHUNPBEkifwceltX6RP4PDIKdtCEQ4vcqrRNvhtAhO9Vo1udkyaeFx5swbY3j11CjzcfrBE=
  - # GPG_PASSPHRASE
  - PYTHON=3.6

before_install:
  - "PY=/usr/bin/python3.6"
  - |
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    sudo $PY get-pip.py --force-reinstall
  - $PY --version
  - sudo $PY -m pip install flair
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn -T 1C test -B

cache:
  directories:
    - $HOME/.m2/repository

before_deploy: ./travis-deployment/before-deploy.sh
deploy:
  provider: script
  script: ./travis-deployment/deploy.sh
  # We need the built artifacts to create their checksums and check if they are already deployed
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^v2.5|master$